package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;

import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */

// Current limits set in TunerConstants.TunerSwerveDrivetrain with comments explaining the reasoning behind the chosen values. Adjust as necessary for your robot's specific needs and characteristics.

public class Drivetrain extends TunerSwerveDrivetrain implements Subsystem 
{
    public static final String TILT_BASED_VISION_UPDATES_ENABLED_KEY = "Vision/EnableTiltBasedPoseUpdate";
    private static final double FLAT_FIELD_ROLL_BASELINE_DEG = 180.0;
    private static final double FLAT_FIELD_PITCH_BASELINE_DEG = 0.0;
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private static final double BUMP_TILT_ENTER_DEG = 8.0;
    private static final double BUMP_TILT_EXIT_DEG = 5.0;
    private static final double BUMP_RECOVERY_HOLD_SEC = 0.35;
    private static final double VISION_ROTATION_RECOVERY_SEC = 1.0;
    private static final double VISION_POSE_RECOVERY_SEC = 1.5;
    private static final double STATIONARY_LINEAR_SPEED_THRESHOLD_MPS = 0.15;
    private static final double STATIONARY_ANGULAR_SPEED_THRESHOLD_RAD_PER_SEC = 0.2;
    private static final Matrix<N3, N1> NORMAL_STATE_STD_DEVS = VecBuilder.fill(0.1, 0.1, 0.1);
    private static final Matrix<N3, N1> BUMP_STATE_STD_DEVS = VecBuilder.fill(0.9, 0.9, 0.2);
    private static final Matrix<N3, N1> NORMAL_VISION_STD_DEVS = VecBuilder.fill(0.6, 0.6, 1.0);
    private static final Matrix<N3, N1> BUMP_VISION_STD_DEVS = VecBuilder.fill(0.2, 0.2, 0.5);

    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;
    private boolean bumpTraversalActive = false;
    private double bumpRecoveryDeadlineSec = 0.0;
    private double visionPoseRecoveryDeadlineSec = 0.0;
    private double visionRotationRecoveryDeadlineSec = 0.0;
    private double robotLinearSpeedMetersPerSec = 0.0;
    private double robotAngularSpeedRadPerSec = 0.0;
    private double robotLinearAccelerationMetersPerSecSq = 0.0;
    private double robotAngularAccelerationRadPerSecSq = 0.0;
    private double lastMotionUpdateSec = Double.NaN;
    private double lastRobotLinearSpeedMetersPerSec = 0.0;
    private double lastRobotAngularSpeedRadPerSec = 0.0;

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public Drivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        setStateStdDevs(NORMAL_STATE_STD_DEVS);
        setVisionMeasurementStdDevs(NORMAL_VISION_STD_DEVS);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public Drivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        setStateStdDevs(NORMAL_STATE_STD_DEVS);
        setVisionMeasurementStdDevs(NORMAL_VISION_STD_DEVS);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public Drivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        setStateStdDevs(NORMAL_STATE_STD_DEVS);
        setVisionMeasurementStdDevs(NORMAL_VISION_STD_DEVS);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }

        updateBumpTraversalState();
        updateMotionStats();
    }

    private void updateBumpTraversalState() {
        double rollTiltDeg = getRollTiltDeg();
        double pitchTiltDeg = getPitchTiltDeg();
        double tiltMagnitudeDeg = Math.hypot(rollTiltDeg, pitchTiltDeg);
        double nowSec = Timer.getFPGATimestamp();
        boolean tiltBasedVisionUpdatesEnabled = SmartDashboard.getBoolean(
                TILT_BASED_VISION_UPDATES_ENABLED_KEY,
                true);

        if (!tiltBasedVisionUpdatesEnabled) {
            visionPoseRecoveryDeadlineSec = 0.0;
            visionRotationRecoveryDeadlineSec = 0.0;
            setBumpTraversalActive(false);
        } else if (tiltMagnitudeDeg >= BUMP_TILT_ENTER_DEG) {
            bumpRecoveryDeadlineSec = nowSec + BUMP_RECOVERY_HOLD_SEC;
            visionPoseRecoveryDeadlineSec = nowSec + VISION_POSE_RECOVERY_SEC;
            visionRotationRecoveryDeadlineSec = nowSec + VISION_ROTATION_RECOVERY_SEC;
            setBumpTraversalActive(true);
        } else if (bumpTraversalActive
                && tiltMagnitudeDeg <= BUMP_TILT_EXIT_DEG
                && nowSec >= bumpRecoveryDeadlineSec) {
            setBumpTraversalActive(false);
        }

        SmartDashboard.putNumber("Drivetrain/RollRawDeg", getRollDeg());
        SmartDashboard.putNumber("Drivetrain/PitchRawDeg", getPitchDeg());
        SmartDashboard.putNumber("Drivetrain/RollDeg", rollTiltDeg);
        SmartDashboard.putNumber("Drivetrain/PitchDeg", pitchTiltDeg);
        SmartDashboard.putNumber("Drivetrain/RollTiltFromFlatDeg", rollTiltDeg);
        SmartDashboard.putNumber("Drivetrain/PitchTiltFromFlatDeg", pitchTiltDeg);
        SmartDashboard.putNumber("Drivetrain/TiltMagnitudeDeg", tiltMagnitudeDeg);
        SmartDashboard.putBoolean("Drivetrain/OnBump", bumpTraversalActive);
        SmartDashboard.putBoolean(TILT_BASED_VISION_UPDATES_ENABLED_KEY, tiltBasedVisionUpdatesEnabled);
        SmartDashboard.putBoolean("Drivetrain/AllowVisionPoseUpdates", shouldAllowVisionPoseUpdate());
        SmartDashboard.putBoolean("Drivetrain/ForceVisionPose", shouldForceVisionPose());
        SmartDashboard.putBoolean("Drivetrain/AllowVisionRotation", shouldUseVisionRotation());
    }

    private void updateMotionStats() {
        ChassisSpeeds speeds = getState().Speeds;
        double linearSpeedMetersPerSec = Math.hypot(speeds.vxMetersPerSecond, speeds.vyMetersPerSecond);
        double angularSpeedRadPerSec = speeds.omegaRadiansPerSecond;
        double nowSec = Timer.getFPGATimestamp();

        if (Double.isNaN(lastMotionUpdateSec)) {
            robotLinearAccelerationMetersPerSecSq = 0.0;
            robotAngularAccelerationRadPerSecSq = 0.0;
        } else {
            double deltaSec = nowSec - lastMotionUpdateSec;
            if (deltaSec > 1e-5) {
                robotLinearAccelerationMetersPerSecSq =
                        (linearSpeedMetersPerSec - lastRobotLinearSpeedMetersPerSec) / deltaSec;
                robotAngularAccelerationRadPerSecSq =
                        (angularSpeedRadPerSec - lastRobotAngularSpeedRadPerSec) / deltaSec;
            }
        }

        robotLinearSpeedMetersPerSec = linearSpeedMetersPerSec;
        robotAngularSpeedRadPerSec = angularSpeedRadPerSec;
        lastRobotLinearSpeedMetersPerSec = linearSpeedMetersPerSec;
        lastRobotAngularSpeedRadPerSec = angularSpeedRadPerSec;
        lastMotionUpdateSec = nowSec;

        SmartDashboard.putNumber("Drivetrain/LinearSpeedMps", robotLinearSpeedMetersPerSec);
        SmartDashboard.putNumber("Drivetrain/LinearAccelMpsSq", robotLinearAccelerationMetersPerSecSq);
        SmartDashboard.putNumber("Drivetrain/AngularSpeedRadPerSec", angularSpeedRadPerSec);
        SmartDashboard.putNumber("Drivetrain/AngularAccelRadPerSecSq", robotAngularAccelerationRadPerSecSq);
    }

    private void setBumpTraversalActive(boolean active) {
        if (bumpTraversalActive == active) {
            return;
        }

        bumpTraversalActive = active;
        setStateStdDevs(active ? BUMP_STATE_STD_DEVS : NORMAL_STATE_STD_DEVS);
        setVisionMeasurementStdDevs(active ? BUMP_VISION_STD_DEVS : NORMAL_VISION_STD_DEVS);
    }
    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds =
    new SwerveRequest.ApplyRobotSpeeds();
    private boolean m_autoBuilderConfigured = false;
    private Rotation2d autoAimTargetHeading = Rotation2d.kZero;
    private double autoAimToleranceDeg = 0.0;
    private boolean autoAimActive = false;
    private double autoAimHeadingOffsetDeg = 0.0;

    public boolean isAutoBuilderConfigured() {
        return m_autoBuilderConfigured;
    }

    public void setAutoAimTargetHeading(Rotation2d targetHeading, double toleranceDeg) {
        autoAimTargetHeading = targetHeading;
        autoAimToleranceDeg = toleranceDeg;
        autoAimActive = true;
    }

    public void clearAutoAimTargetHeading() {
        autoAimActive = false;
        autoAimToleranceDeg = 0.0;
    }

    public void adjustAutoAimHeadingOffsetDeg(double deltaDeg) {
        autoAimHeadingOffsetDeg += deltaDeg;
    }

    public double getAutoAimHeadingOffsetDeg() {
        return autoAimHeadingOffsetDeg;
    }

    public Rotation2d getAutoAimHeadingOffset() {
        return Rotation2d.fromDegrees(autoAimHeadingOffsetDeg);
    }

    public void resetAutoAimHeadingOffset() {
        autoAimHeadingOffsetDeg = 0.0;
    }

    public boolean isRotAligned() {
        if (!autoAimActive) {
            return false;
        }

        double headingErrorDeg = Math.toDegrees(
                MathUtil.angleModulus(autoAimTargetHeading.minus(getState().Pose.getRotation()).getRadians()));
        SmartDashboard.putNumber("Drivetrain/AutoAimHeadingOffsetDeg", autoAimHeadingOffsetDeg);
        return Math.abs(headingErrorDeg) <= autoAimToleranceDeg;
    }

    public double getGyroYawDeg() {
        return getPigeon2().getYaw().getValueAsDouble();
    }

    public double getRollDeg() {
        return getPigeon2().getRoll().getValueAsDouble();
    }

    public double getPitchDeg() {
        return getPigeon2().getPitch().getValueAsDouble();
    }

    public double getRollTiltDeg() {
        return getTiltFromFlatDeg(getRollDeg(), FLAT_FIELD_ROLL_BASELINE_DEG);
    }

    public double getPitchTiltDeg() {
        return getTiltFromFlatDeg(getPitchDeg(), FLAT_FIELD_PITCH_BASELINE_DEG);
    }

    private double getTiltFromFlatDeg(double axisAngleDeg, double flatBaselineDeg) {
        return MathUtil.inputModulus(
                axisAngleDeg - flatBaselineDeg,
                -180.0,
                180.0);
    }

    public Rotation2d getRawHeading() {
        return getState().RawHeading;
    }

    public boolean isTraversingBump() {
        return bumpTraversalActive;
    }

    public double getRobotLinearSpeedMetersPerSec() {
        return robotLinearSpeedMetersPerSec;
    }

    public double getRobotLinearAccelerationMetersPerSecSq() {
        return robotLinearAccelerationMetersPerSecSq;
    }

    public double getRobotAngularAccelerationRadPerSecSq() {
        return robotAngularAccelerationRadPerSecSq;
    }

    public double getRobotAngularSpeedRadPerSec() {
        return robotAngularSpeedRadPerSec;
    }

    public boolean isEffectivelyStationary() {
        return robotLinearSpeedMetersPerSec <= STATIONARY_LINEAR_SPEED_THRESHOLD_MPS
                && Math.abs(robotAngularSpeedRadPerSec) <= STATIONARY_ANGULAR_SPEED_THRESHOLD_RAD_PER_SEC;
    }

    public boolean shouldAllowVisionPoseUpdate() {
        return bumpTraversalActive
                || Timer.getFPGATimestamp() <= visionPoseRecoveryDeadlineSec
                || isEffectivelyStationary();
    }

    public boolean shouldForceVisionPose() {
        return bumpTraversalActive || Timer.getFPGATimestamp() <= visionPoseRecoveryDeadlineSec;
    }

    public boolean shouldUseVisionRotation() {
        return bumpTraversalActive || Timer.getFPGATimestamp() <= visionRotationRecoveryDeadlineSec;
    }

    public Pose2d useGyroHeadingForPose(Pose2d pose) {
        return new Pose2d(pose.getTranslation(), getState().Pose.getRotation());
    }

    public void resetPoseFromVision(Pose2d visionPose, boolean useVisionRotation) {
        if (useVisionRotation) {
            resetPose(visionPose);
            return;
        }

        Translation2d translation = visionPose.getTranslation();
        resetTranslation(translation);
    }
    
    private void configureAutoBuilder() 
    {
        try 
        {
            var config = RobotConfig.fromGUISettings();
            AutoBuilder.configure
            (
                () -> getState().Pose,   // Supplier of current robot pose
                this::resetPose,         // Consumer for seeding pose against auto
                () -> getState().Speeds, // Supplier of current robot speeds
                // Consumer of ChassisSpeeds and feedforwards to drive the robot
                (speeds, feedforwards) -> setControl
                (
                    m_pathApplyRobotSpeeds.withSpeeds(speeds)
                        .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                        .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())
                ),
                new PPHolonomicDriveController
                (
                    // PID constants for translation
                    new PIDConstants(10, 0, 0),    // .64, 0, 0 -3/6/25  // CT: 5, 0, 0
                    // PID constants for rotation
                    new PIDConstants(5, 0, 0)      // 25, 0, 0 -3/6/25  // CT: 5, 0, 0
                ),
                config,
                // Assume the path needs to be flipped for Red vs Blue, this is normally the case
                () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
                this // Subsystem for requirements
            );
            m_autoBuilderConfigured = true;
        } 
        catch (Exception ex) 
        {
            m_autoBuilderConfigured = false;
            DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
        }
    }
}
